version: "3"

networks:
    portfolio:

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql:/var/lib/mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3349:3306"
    networks:
      - portfolio

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    depends_on:
      - php
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - portfolio

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - portfolio

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - portfolio 

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - portfolio
